terminate called after throwing an instance of 'std::logic_error'
  what():  you want to return a variable which was not declared
Aborted

return code: 134
